### ISSUE TITLE
help with Mapbox Directions

### ISSUE THREAD

**Issue by hsianchen** [willychang21/MapboxARGame#10]
Hi,I'm trying to use DirectionsFactory. I  want to change the two specify waypoints to user current location and user's destination. How can I do ?
May I see your hierarchy of unity? I am really  a newcomer in  Mapbox and unity.

**Comment by hsianchen** [comment]
@willychang21 你好，我想請問一下你是怎麼做出導航的路線的呢?
我有把Directions加入我的project中但還不知道怎麼使用，想問問看你是怎麼解決的
我的Hierarchy:
![Hierarchy](https://user-images.githubusercontent.com/25290748/54491096-a5a94780-48f6-11e9-989b-e7f3cf2fb0eb.jpg)
Directions裡的Script:
![Directions](https://user-images.githubusercontent.com/25290748/54491099-ab9f2880-48f6-11e9-8886-79d2a8d86eb8.jpg)
我的Directions幾乎是初始的狀態，沒有做什麼調整，請問你是加入什麼script讓路線顯示在AR跟平面地圖上呢?
謝謝!

**Comment by willychang21** [comment]
@hsianchen  我將我的專案傳上來了你可以參考一下

**Comment by hsianchen** [comment]
@willychang21 好的，感謝~~我已經解決了~
謝謝!
