### ISSUE TITLE
Direction 問題

### ISSUE THREAD

**Issue by cyje66** [willychang21/MapboxARGame#11]
@willychang21  請問你是怎麼做出按下map上的建築物就可以顯示Directions 的功能?
目前我已經可以將路線顯示出來了，如下:
![Scene](https://user-images.githubusercontent.com/23631550/55383436-c1e5ef00-555a-11e9-99eb-77fbad390e0f.jpg)

我試著做出按下建築物就可以出現導航到那棟建築物的路線，但不知道從何下手，希望您可以幫幫忙
感謝!

**Comment by willychang21** [comment]
@cyje66 我將我的專案傳上來了你可以參考一下
