### ISSUE TITLE
Tileset數量上限問題

### ISSUE THREAD

**Issue by myong3** [willychang21/MapboxARGame#4]
![default](https://user-images.githubusercontent.com/39517954/40527039-bef16380-601c-11e8-8a48-df72e4d93b2f.JPG)

**Comment by willychang21** [comment]
https://github.com/mapbox/mapbox-unity-sdk/issues/815

**Comment by willychang21** [comment]
Change

`Mapbox -> Setup -> Configuration -> MBTiles Cache Size (# of tiles)`

to `0.`
